#!/usr/bin/env bash
set -o errexit

DOMAIN=${1:-magento.test}
VERSION=${2:-2.4.7}
EDITION=${3:-community}

curl -s https://raw.githubusercontent.com/piotrkwiecinski/docker-magento/traefik/lib/template | bash

bin/init-project-env "${DOMAIN}"

# &&'s are used below otherwise onelinesetup script fails/errors after bin/download
bin/download "${VERSION}" "${EDITION}" \
  && bin/setup "${DOMAIN}"
