#!/usr/bin/env bash

if [ -d "./bin" ]; then
  echo "Error: The current directory is not empty. Please remove all contents within this directory and try again."
  exit 1
fi

TEMPLATE_REPOSITORY=${TEMPLATE_REPOSITORY:-markshust/docker-magento}
TEMPLATE_REPOSITORY_BRANCH=${TEMPLATE_REPOSITORY_BRANCH:-master}

git init -qqq
git remote add origin https://github.com/"${TEMPLATE_REPOSITORY}"
git fetch origin -qqq
git checkout origin/"${TEMPLATE_REPOSITORY_BRANCH}" -- compose

mv compose/* ./
mv compose/.gitignore ./
mv compose/.vscode ./
rm -rf compose .git
git init

# Ensure these are created so Docker doesn't create them as root
mkdir -p ~/.composer ~/.ssh
