name: "Script Tests"
on:
  push:
    branches: ["master"]
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:

      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.2.1

      - name: Check out code
        uses: actions/checkout@v1

      - name: Install dependencies
        run: |
          sudo apt-get -y update && sudo apt-get install -y ca-certificates

      - name: Setup PHP, with composer
        uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        with:
          php-version: '7.4'

      - name: Test
        run: |
          which composer
          echo hash composer
          composer config --global http-basic.repo.magento.com '${{ secrets.MAGENTO_REPO_USERNAME }}' '${{ secrets.MAGENTO_REPO_PASSWORD }}'
          ls ~/.composer/auth.json
          bats compose/tests
