name: "Script Tests"

on:
  push:
    branches: ["master"]
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:

      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.2.1

      - name: Check out code
        uses: actions/checkout@v1

      - name: Install dependencies
        run: |
          command -v update-ca-certificates > /dev/null || sudo apt-get -y update && sudo apt-get install -y ca-certificates

      - name: Setup PHP, with composer
        uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        with:
          php-version: '7.4'
          tools: composer:v1
      - name: Test
        shell: bash
        env:
          COMPOSE_INTERACTIVE_NO_CLI: 1
        run: |
          echo '${{ secrets.COMPOSER_AUTH_JSON }}' > ~/.composer/auth.json
          bats compose/tests/status.bats compose/tests/download.bats
          bats compose/tests/bash.bats
